In [1]:
import numpy as np  #importing numpy

In [2]:
np.arange(5)  #creating an array using arange function

array([0, 1, 2, 3, 4])

In [3]:
np.arange(0,10) #alternate method

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,10,2) #using step function to filter data

array([0, 2, 4, 6, 8])

In [6]:
np.zeros(3) # array of zeros ( linear array )

array([ 0.,  0.,  0.])

In [8]:
np.zeros((2,3)) # array of zeros in matrix format , 2 rows and 3 columns

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [7]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [9]:
np.ones(4) # same thing for ones

array([ 1.,  1.,  1.,  1.])

In [9]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [10]:
np.linspace(0,5,10)  # linear step function i,e 0 to 5 in 10 steps and it's a linear matrix

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [11]:
np.linspace(0,5,100) # same thing using 100 steps

array([ 0.        ,  0.05050505,  0.1010101 ,  0.15151515,  0.2020202 ,
        0.25252525,  0.3030303 ,  0.35353535,  0.4040404 ,  0.45454545,
        0.50505051,  0.55555556,  0.60606061,  0.65656566,  0.70707071,
        0.75757576,  0.80808081,  0.85858586,  0.90909091,  0.95959596,
        1.01010101,  1.06060606,  1.11111111,  1.16161616,  1.21212121,
        1.26262626,  1.31313131,  1.36363636,  1.41414141,  1.46464646,
        1.51515152,  1.56565657,  1.61616162,  1.66666667,  1.71717172,
        1.76767677,  1.81818182,  1.86868687,  1.91919192,  1.96969697,
        2.02020202,  2.07070707,  2.12121212,  2.17171717,  2.22222222,
        2.27272727,  2.32323232,  2.37373737,  2.42424242,  2.47474747,
        2.52525253,  2.57575758,  2.62626263,  2.67676768,  2.72727273,
        2.77777778,  2.82828283,  2.87878788,  2.92929293,  2.97979798,
        3.03030303,  3.08080808,  3.13131313,  3.18181818,  3.23232323,
        3.28282828,  3.33333333,  3.38383838,  3.43434343,  3.48

In [12]:
np.eye(4)  #creating identity matrix 

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [13]:
np.random.rand(5) # random integers in linear matrix

array([ 0.4271981 ,  0.87202266,  0.75229904,  0.68385011,  0.47003767])

In [14]:
np.random.rand(5,5) # same thing in 5X5 matrix

array([[ 0.39281302,  0.59946252,  0.71974967,  0.28566607,  0.179938  ],
       [ 0.69854979,  0.80773959,  0.31199447,  0.64048398,  0.1415333 ],
       [ 0.74416402,  0.2147644 ,  0.89570172,  0.10133362,  0.9858204 ],
       [ 0.94520461,  0.21798336,  0.79369305,  0.27814913,  0.4156869 ],
       [ 0.98413835,  0.65878712,  0.1874717 ,  0.63279714,  0.35719112]])

In [15]:
np.random.rand(5)

array([ 0.59223061,  0.93814919,  0.69751097,  0.6622115 ,  0.18370868])

In [16]:
np.random.randn(2)

array([ 0.40614628, -0.09463674])

In [17]:
np.random.randn(4,4)

array([[-0.55428847, -1.01153544, -0.7730978 ,  1.57199254],
       [-0.49399566,  0.05743661, -0.57090405, -0.50868201],
       [ 1.44820393,  0.12066965, -0.59910053, -1.5909007 ],
       [ 0.61571925,  0.5500747 , -1.53358687, -0.78478548]])

In [18]:
np.random.randint(1,100) # random in between 1 and 100

6

In [15]:
np.random.randint(1,100,10) # 10 random integers

array([12, 82, 22, 22, 29, 48, 36, 40, 94, 83])

In [18]:
arr = np.arange(25)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
ranarr = np.random.randint(0,50,10)

In [21]:
ranarr

array([26,  7, 22, 37, 48, 38, 19, 38, 27, 31])

In [22]:
arr.reshape(5,5) # reshaping in 5X5 matrix i.e 25 elements = 5X5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
ranarr

array([21, 12, 10,  9, 18, 36, 24, 17,  8, 31])

In [27]:
ranarr.max()

36

In [28]:
ranarr.min()

8

In [29]:
ranarr

array([21, 12, 10,  9, 18, 36, 24, 17,  8, 31])

In [25]:
ranarr.argmax() #index of max

4

In [26]:
ranarr.argmin() # index of min

1

In [32]:
arr.shape

(25,)

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arr = arr.reshape(5,5)

In [35]:
arr.shape

(5, 5)

In [36]:
arr.dtype

dtype('int64')

In [37]:
my_list = [1,2,3]

In [38]:
art = np.array(my_list)

In [39]:
art

array([1, 2, 3])

In [40]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [41]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
from numpy.random import randint

In [43]:
randint(2,10)

7