In [27]:
import numpy as np

In [28]:
arr = np.arange(0,11)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr[8]

8

In [31]:
arr[1:5] #slicing and dicing

array([1, 2, 3, 4])

In [32]:
arr[0:5] #same thing

array([0, 1, 2, 3, 4])

In [33]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [34]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [35]:
arr[0:5] = 100 # replacing 0 to 4 with 100's

In [36]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [37]:
arr = np.arange(0,11)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
slice_of_arr = arr[0:6] #slice of arr as slice

In [40]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [41]:
slice_of_arr[:] = 99 #replacing whole with 99's

In [42]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [43]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [44]:
arr_copy = arr.copy() #making a copy

In [45]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [46]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [47]:
arr_copy[:] = 100 #making a copy with 100's

In [48]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [49]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Now we can look at indexing 2D Arrays

In [50]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])  #making 2d array

In [51]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

arr_2d

In [52]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [53]:
arr_2d[0][0] #indexing elements

5

In [54]:
arr_2d[0]

array([ 5, 10, 15])

In [55]:
arr_2d[1][1]

25

In [56]:
arr_2d[2][1]

40

In [57]:
arr_2d[2,1]

40

In [58]:
arr_2d[1,2]

30

In [59]:
arr_2d[:2,1:] #showing a part of matrix

array([[10, 15],
       [25, 30]])

In [60]:
arr_2d[:2] #same

array([[ 5, 10, 15],
       [20, 25, 30]])

In [61]:
arr_2d[1: , :2] #same

array([[20, 25],
       [35, 40]])

In [62]:
arr = np.arange(1,11)

In [63]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
bool_arr = arr > 5 #conditional indexing

In [65]:
bool_arr #output

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [66]:
arr[bool_arr] #showing a part which is True

array([ 6,  7,  8,  9, 10])

In [67]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [68]:
arr[arr < 3]

array([1, 2])

In [69]:
arrr_2d = np.arange(50).reshape(5,10) #making 2d array and reshaping

In [70]:
arrr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [71]:
arrr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [72]:
arrr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])